---

- name: make sure we have certs and https
  apt:
    update_cache: true
    cache_valid_time: 3600
    name:
      - apt-transport-https
      - ca-certificates
      - software-properties-common

- name: add key
  apt_key:
    url: https://yum.dockerproject.org/gpg
    id: 58118E89F3A912897C070ADBF76221572C52609D
    # was keyserver: hkp://p80.pool.sks-keyservers.net:80

- name: add repo to sources.list
  apt_repository:
    repo='deb https://apt.dockerproject.org/repo debian-jessie main'
    # we would have to delete old repos, but it's a fresh install, so never mind

# verify the apt is pulling from the right repo: $ apt-cache policy docker-engine
# skipping, because this is quite optional and I'm not sure how to check this here

- name: install docker
  apt:
    update_cache: true
    cache_valid_time: 3600
    name:
      - docker-engine
    state: latest

# - name: start docker daemon
#   service:
#     name: docker
#     state: started

# - name: add the docker group
#   group: name=docker state=present

# - name: add admin to the docker group
#   user:
#     name: admin
#     groups: docker
#     append: yes
#   notify:
#     - restart docker daemon   # don't know why they have this step in docs, should probably work without it

- name: install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.11.1/docker-compose-{{ ansible_system }}-{{ ansible_machine }}
    dest: /usr/local/bin/docker-compose
    mode: 0755
    checksum: sha256:8749e21ee7c6f99f01e666bd3d655012efb1a75aafc8ea1c77dd433b88d53b34
    backup: yes

- name: make sure docker-compose owner is root:root, 0755
  file: path=/usr/local/bin/docker-compose owner=root group=root mode=0755

# - name: add a user, which can run docker containers
#   user:
#     name: '{{ username }}'
#     groups: docker
#     append: yes
#     shell: /bin/bash
    
# - name: add key of the user to authorized_keys
#   authorized_key:
#     user: '{{ username }}'
#     key: '{{ public_key_url }}'

#   handlers:
# - name: restart docker daemon
#   service:
#     name: docker
#     state: restarted


# TODO: add to the end
# - name: for dnsdock 
#   lineinfile: dest="/lib/systemd/system/docker.service" regexp="^ExecStart=/usr/bin/dockerd -H fd://" line="ExecStart=/usr/bin/dockerd -H fd:// --bip=172.17.0.1/24 --dns=172.17.0.1"





